/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiDogsRouteImport } from './routes/api/dogs'
import { Route as ApiBreedsRouteImport } from './routes/api/breeds'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDogsRoute = ApiDogsRouteImport.update({
  id: '/api/dogs',
  path: '/api/dogs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBreedsRoute = ApiBreedsRouteImport.update({
  id: '/api/breeds',
  path: '/api/breeds',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/breeds': typeof ApiBreedsRoute
  '/api/dogs': typeof ApiDogsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/breeds': typeof ApiBreedsRoute
  '/api/dogs': typeof ApiDogsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/breeds': typeof ApiBreedsRoute
  '/api/dogs': typeof ApiDogsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/breeds' | '/api/dogs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/breeds' | '/api/dogs'
  id: '__root__' | '/' | '/api/breeds' | '/api/dogs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBreedsRoute: typeof ApiBreedsRoute
  ApiDogsRoute: typeof ApiDogsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dogs': {
      id: '/api/dogs'
      path: '/api/dogs'
      fullPath: '/api/dogs'
      preLoaderRoute: typeof ApiDogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/breeds': {
      id: '/api/breeds'
      path: '/api/breeds'
      fullPath: '/api/breeds'
      preLoaderRoute: typeof ApiBreedsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBreedsRoute: ApiBreedsRoute,
  ApiDogsRoute: ApiDogsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
